version: '2'

services:
  web:
    build: .
    ports:
    - 8000:8000
    links:
    - database
    environment:
    - USER
  database:
    image: postgres
    environment:
      # don't do this in production -- this works for test/dev
      POSTGRES_PASSWORD: oss-attribution-builder-postgres
    volumes:
    - ./docs/schema.sql:/docker-entrypoint-initdb.d/init.sql
  selenium:
    # use standalone-chrome-debug if you want to VNC in and watch
    image: selenium/standalone-chrome
    ports:
    - 4444:4444
    - 5900:5900
    links:
    - web
    environment:
      SCREEN_WIDTH: 1500
      SCREEN_HEIGHT: 2000
    shm_size: 2G
